config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets do
    collection do
      get :search
     end
     resources :comments, only: :create
     resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/baby_age.rb
class BabyAge < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '0歳0ヶ月~0歳3ヶ月' },
    { id: 3, name: '0歳4ヶ月~0歳7ヶ月' },
    { id: 4, name: '0歳8ヶ月~0歳11ヶ月' },
    { id: 5, name: '1歳0ヶ月~1歳3ヶ月' },
    { id: 6, name: '1歳4ヶ月~1歳7ヶ月' },
    { id: 7, name: '1歳8ヶ月~1歳11ヶ月' },
    { id: 8, name: '2歳0ヶ月~2歳3ヶ月' },
    { id: 9, name: '2歳4ヶ月~2歳7ヶ月' },
    { id: 10, name: '2歳8ヶ月~2歳11ヶ月' },
    { id: 11, name: '3歳0ヶ月~3歳3ヶ月' },
    { id: 12, name: '3歳4ヶ月~3歳7ヶ月' },
    { id: 13, name: '3歳8ヶ月~3歳11ヶ月' },
    { id: 14, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/models/baby_gender.rb
class BabyGender < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男の子' },
    { id: 3, name: '女の子' }

  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '食事' },
    { id: 3, name: '遊び' },
    { id: 4, name: 'イヤイヤ期' },
    { id: 5, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  has_one_attached :image

  validates :text, presence: true
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '便利' },
    { id: 3, name: '危険' },
    { id: 4, name: '悩み' },
    { id: 5, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_one_attached :image
  has_one_attached :video

  scope :search, lambda { |search_params|
    return if search_params.blank?

    content_like(search_params[:content])
      .category_id_is(search_params[:category_id])
      .condition_id_is(search_params[:condition_id])
      .baby_age_id_is(search_params[:baby_age_id])
      .baby_gender_id_is(search_params[:baby_gender_id])
  }

  scope :content_like, ->(content) { where('content LIKE ?', "%#{content}%") if content.present? }
  scope :category_id_is, ->(category_id) { where(category_id: category_id) if category_id.present? }
  scope :condition_id_is, ->(condition_id) { where(condition_id: condition_id) if condition_id.present? }
  scope :baby_age_id_is, ->(baby_age_id) { where(baby_age_id: baby_age_id) if baby_age_id.present? }
  scope :baby_gender_id_is, ->(baby_gender_id) { where(baby_gender_id: baby_gender_id) if baby_gender_id.present? }

  validates :content, presence: true
  
  with_options presence: true, numericality: { other_than: 1 } do
    validates :category_id
    validates :condition_id
    validates :baby_age_id
    validates :baby_gender_id
  end

  validate :image_content_type, if: :was_attached?
  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg', 'image/GIF','image/BMP']
    errors.add(:image, "の拡張子が間違っています") unless image.content_type.in?(extension)
  end

  validate :video_content_type, if: :has_attached?

  def video_content_type
    extension = ['video/mp4']
    errors.add(:video, "の拡張子が間違っています") unless video.content_type.in?(extension)
  end


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :condition
  belongs_to :baby_age
  belongs_to :baby_gender


  def was_attached?
    self.image.attached?
  end

  def has_attached?
    self.video.attached?
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes
  def already_liked?(tweet)
    likes.exists?(tweet_id: tweet.id)
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字どちらも含んでください'
  with_options presence: true do
    validates :nickname, length: { maximum: 10 }
    validates :baby_name
    validates :baby_birthday
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :baby_name, :baby_birthday])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_tweet, only: [:edit, :destroy, :show, :update]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.includes(:user).order('created_at DESC')
    @search_params = tweet_search_params
    @tweet = Tweet.search(@search_params).includes(:user)
    
  end

  def new
    @tweet = Tweet.new
    
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user).order('created_at DESC')
    @like = Like.new
  end

  def search
    @search_params = tweet_search_params
    @tweets = Tweet.search(@search_params).order('created_at DESC')
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :image, :category_id, :condition_id, :baby_age_id, :baby_gender_id,
                                  :video).merge(user_id: current_user.id)
  end

  def tweet_search_params
    params.fetch(:search, {}).permit(:content, :category_id, :condition_id, :baby_age_id, :baby_gender_id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def contributor_confirmation
    redirect_to action: :index unless current_user.id == @tweet.user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.order('created_at DESC')
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :baby_name, :baby_birthday)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oriapp34562</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="index.js"></script>
    <script src="https://kit.fontawesome.com/bb220ab896.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
      <p>
        Copyright(C) Ikupapa ALL RIGHTS RESERVED. 
      </p>
</footer>　　

app/views/shared/_form.html.erb
<%= form_with(model: @tweet, local: true) do |f| %>
<%= render "shared/error_messages", model: f.object %>
     <div class="tweet-image-video">※画像と動画がなくても投稿できます</div>
　　　 <div class = "tweet-image-view">
      <p>画像（JPEG,PNG,GIF,BMPのみ）</p>
        <%= f.file_field :image, id: "image" %>
      </div>
      <div id="image-list"></div>
      <div class ="tweet-video-view">
      <p>動画（mp４のみ）</p>
        <%= f.file_field :video, id: "video" %>
     </div>
      <div id="video-list"></div>  
      <div class="content">
      <%= f.text_area  :content, id: "content", placeholder: "概要",class:"tweet-content-view" %>
      </div>
      <div class = "category-select">カテゴリー(選択してください）
      <p>状況</p>
      <div class="category">
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category_id"}) %>
      </div>
      <p>状態</p>
      <div class="condition">
      <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"select-box", id:"condition_id"}) %>
       </div>
       <p>時期</p>
       <div class="baby-age">
      <%= f.collection_select(:baby_age_id, BabyAge.all, :id, :name, {}, {class:"select-box", id:"baby_age_id"}) %>
      </div>
      <p>性別</p>
       <div class="baby-gender">
      <%= f.collection_select(:baby_gender_id, BabyGender.all, :id, :name, {}, {class:"select-box", id:"Baby_gender_id"}) %>
      </div>
      </div>
      <%= f.submit "SEND" ,class:"tweet-btn" %>
    <% end %>
 

app/views/shared/_header.html.erb
  <header class="header">
      <div class="heading">
      <h1 class="title"><a href="/"><i class="fas fa-baby"></i>IkuPapa</a></h1>
      </div>
      <div class= "user-nav">
        <% if user_signed_in? %>
          <ul class="user_nav_lists">
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "post"%></li>
            <li><%= link_to "Account編集", edit_user_path(current_user),class: "post"%></li>
            <li><%= link_to "投稿", new_tweet_path, class: "post" %></li>
          </ul>
        <% else %> 
           <ul class="user_nav_lists"> 
             <li><%= link_to "ログイン", new_user_session_path, class: "post" %></li>
             <li><%= link_to "新規登録（無料）", new_user_registration_path, class: "post" %></li>
           </ul>
        <% end %> 
     </div>
     </div> 
  </header>
   <% if user_signed_in? %>
      <div class="greeting">
       こんにちは、
         <%= link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", class: :greeting__link%>
        、
         <%= link_to "#{current_user.baby_name}さん", "/users/#{current_user.id}", class: :greeting__link%>
         （<%= (Date.today.strftime("%Y%m%d").to_i - current_user.baby_birthday.strftime("%Y%m%d").to_i) / 10000%>歳
         <% if (Date.today.strftime("%m%d").to_i - current_user.baby_birthday.strftime("%m%d").to_i) / 100 >= 0  %>
         <%= (Date.today.strftime("%m%d").to_i - current_user.baby_birthday.strftime("%m%d").to_i) / 100 %>ヶ月）
         <% else %> 
          <%= (Date.today.strftime("%m%d").to_i - current_user.baby_birthday.strftime("%m%d").to_i) / 100 + 12 %>ヶ月）
         <% end %> 
         <% end %> 
      </div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_second_header.html.erb
<header class="header">
      <div class="heading">
      <h1 class="title"><a href="/"><i class="fas fa-baby"></i>IkuPapa</a></h1>
      </div> 
</header>

app/views/shared/_tweet.html.erb
   <div class="tweet-tweet">
    <time datetime="<%= tweet.created_at %>">
            <%="投稿日："+ time_ago_in_words(tweet.created_at) + "前"%>
          </time>
          
   <div  class='tweet-img-content'> 
       <%= image_tag tweet.image.variant(resize: '400x400'), class: 'tweet-image' if tweet.image.attached?%>
       
       <% if tweet.video.attached? %> <video src="<%= rails_blob_path(tweet.video)%>" type="video/mp4" controls class="tweet-video" ></video>
       </div>
 　　　　<% end %>  
   <div class="more"> 
      <p><%= tweet.content %></p>
   </div>
   <span class="name">
      <i class="fa fa-user"></i><strong>投稿者：<%= link_to tweet.user.nickname, "/users/#{tweet.user_id}" ,class:"name-list"%></strong>
      </span>
      (<i class="far fa-thumbs-up fa-fw fa-lg faa-tada animated"></i><%= tweet.users.count %>件)
   <ul class="more_list">
          <li>
            <i class="fa fa-comment-o"></i><%= link_to 'コメント', tweet_path(tweet.id), method: :get ,class:"menu-list"%>(<%= tweet.comments.count %>件)
          </li>
          <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li>
            <i class="fa fa-edit"></i><%= link_to '編集', edit_tweet_path(tweet.id), method: :get,class:"menu-lists" %>
          </li>
          <li>
            <i class="fa fa-trash-o"></i><%= link_to '削除', tweet_path(tweet.id), data: {confirm: '本当に削除しますか？'}, method: :delete,class:"menu-lists" %>
          </li>
          <% end %>
        </ul>
   </div>
   </div>

app/views/tweets/destroy.html.erb
<%= render partial: "shared/second_header"%>

<div class="contents-destroy">
  <div class="success">
    <h4>削除が完了しました。</h4>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render partial: "shared/second_header"%>

<div class="tweet-contents">
 <div class="tweet-header ">
  <div class="tweet-main">
    <div class=tweet-text>編集する</div>
  <%= render partial: "shared/form"%>
<%= render partial: "shared/footer"%>

app/views/tweets/index.html.erb
<%= render partial: "shared/header"%>

<div class="contents">

  <div class="first-view">
       <%= link_to image_tag("cache_Messagep37593.jpeg", class:"top-image"), "#" %>
  </div>
  <div class="contents-top">
   <h2>papaにしかわからない楽しさや悩みを共有してみませんか？<br>それを共有することで今日も笑顔になれる家族がたくさんいます！<br>まずは気軽に投稿してみよう！！</h2>
  </div>
  <div class="contents-middle">
   <h3>何ができるの？</h3>
   <h6>食事、遊び、イヤイヤ期の悩み事をユーザー同士で共有して解決しましょう！</h6>
   <ul class="contents-middle-lists">
        <li class="li-style">  
          <%= link_to image_tag("detail1_2fc7d375-0df9-411d-bca0-f153e2f57af9.jpeg", class:"middle-image"), "#" %>
          <h4 class="middle-list"><span class= "content-blue">1,食事</span><br>・離乳食のあげる時期によって食べれるものが違う<br>・冷凍することで準備が楽にもなる<br>・お父さんが食べる見本を見せたら食べるかもしれない！</h4>
        <li class="li-style">  
          <%= link_to image_tag("IMG_5941.jpeg", class:"middle-image"), "#" %>
          <h4 class="middle-list"><span class= "content-blue">２,遊び</span><br>・この時期の子供に適切な遊びはなんだろう<br>・与えるおもちゃは何がいいだろう<br>・お父さんが絵本を読んでくれたら喜ぶかもしれない！</h4>
        <li class="li-style">  
          <%= link_to image_tag("IMG_8693.jpg", class:"middle-image"), "#" %>
          <h4 class="middle-list"><span class= "content-blue">3,イヤイヤ期</span><br>・出た！！のけぞりポーズ<br>・いったい何をすればおさまるの？<br>・注意点をそらす別の何かをすればおさまるかも！</h4>
        </li>
        <h4 class="middle-content"><span class= "content-red">悩んでることの対処法を検索しよう！</span><br>下記の検索ボタンを押していただくことで投稿の内容を絞ってください！<br>入力項目が一つだけでも絞ることができます！<br>なんでも調べてみてください！</h4>
       <div class = check-js id="check"><i class="fas fa-search"></i>検索</div>
   </ul>

   <%= form_with(scope: :search, url: search_tweets_path, method: :get, local: true) do |f| %>
   <div class = "check-contents-js" id="pull-down">
     <div class="check-contents">
      <div class="check-content">
      <p>投稿</p>
      <%= f.text_field :content, value: @search_params[:content], placeholder: '投稿ワード' , class:"content-box"%>
      </div>
      <div class="check-content">
      <p>状況</p>
      <%= f.collection_select:category_id, Category.all, :id, :name, {include_blank: '指定なし', selected: @search_params[:category_id]}, {class:'check-box'} %> 
      </div>
      <div class="check-content">
      <p>状態</p>
      <%= f.collection_select:condition_id, Condition.all, :id, :name, {include_blank: '指定なし', selected: @search_params[:condition_id]}, {class:'check-box'} %> 
       </div>
       <div class="check-content">
       <p>時期</p>
      <%= f.collection_select:baby_age_id, BabyAge.all, :id, :name, {include_blank: '指定なし', selected: @search_params[:baby_age_id]}, {class:'check-box'} %>
     </div>
       <div class="check-content">
       <p>性別</p>
      <%= f.collection_select:baby_gender_id, BabyGender.all, :id, :name, {include_blank: '指定なし',selected: @search_params[:baby_gender_id]} , {class:'check-box'}%> 
      </div>
     </div>
      <%= f.submit"この条件で検索する",class:"check-btn"%>
    </div>
<% end %>
  <h5>投稿一覧</h5>
  <div class="contents-row">
   <% @tweets.each do |tweet| %>
   <%= render partial: "shared/tweet", locals: { tweet: tweet } %>
  <% end %>
  </div>
</div>
<%= render partial: "shared/footer"%>

app/views/tweets/new.html.erb
<%= render partial: "shared/second_header"%>

<div class="tweet-contents">
 <div class="tweet-header">
  <div class="tweet-main">
    <div class=tweet-text>投稿</div>
    
    <%= render partial: "shared/form"%>
    </div>
 </div>
</div>
<%= render partial: "shared/footer"%>
 

app/views/tweets/search.html.erb
<%= render partial: "shared/second_header"%>
<% unless @search_params.blank? %>
 <% @tweets.each do |tweet| %>
   <div class="tweet-tweet-comment">
   <div class='tweet-img-content'> 
       <%= image_tag tweet.image.variant(resize: '400x400'), class: 'tweet-image' if tweet.image.attached? %>
       <% if tweet.video.attached? %> <video src="<%= rails_blob_path(tweet.video)%>" type="video/mp4" controls class="tweet-video" ></video>
   　　<% end %>

       <div class="more"> 
         <p><%= tweet.content %></p>
           <span class="name">
           <strong>投稿者：<%= link_to tweet.user.nickname, "/users/#{tweet.user_id}" %></strong>
           </span>
   </div>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', tweet_path(tweet.id), method: :get %>
          </li>
          <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li>
            <%= link_to '編集', edit_tweet_path(tweet.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
          </li>
          <% end %>
        </ul>
   </div>
   
   </div>
  <% end %>
<% end %>
<%= render partial: "shared/footer"%>

app/views/tweets/show.html.erb
<%= render partial: "shared/second_header"%>

<div class="tweet-tweet-comment">
   <div class='tweet-img-content'> 
       <%= image_tag @tweet.image.variant(resize: '400x400'), class: 'tweet-image' if @tweet.image.attached? %>
       <% if @tweet.video.attached? %> <video src="<%= rails_blob_path(@tweet.video)%>" type="video/mp4" controls class="tweet-video" ></video>
       <% end %>
       
       
       <div class="more"> 
         <p><%= @tweet.content %></p>
       </div>
         <div class = "click-js" id="click-js">いいね (<i class="far fa-thumbs-up fa-fw fa-lg faa-tada animated"></i><%= @tweet.likes.count %>) </div>
         <div class = "iine-btn">
       <% if current_user.already_liked?(@tweet) %>
       <%= button_to 'いいねを取り消す', tweet_like_path(@tweet), method: :delete ,class:"comment-btn"%>
       <% else %>
       <%= button_to'いいね!', tweet_likes_path(@tweet),class:"comment-btn" %>
       <% end %>
       </div>
       <div class="click-iine" id="pull-down-iine">
       <% @tweet.users.each do |user| %>
       <li><%= user.nickname %></li>
       <% end %>
       </div>
        <ul class="more_list">
         <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <li>
            <i class="fa fa-edit"></i><%= link_to '編集', edit_tweet_path(@tweet.id), method: :get,class:"menu-lists" %>
          </li>
          <li>
            <i class="fa fa-trash-o"></i><%= link_to '削除', tweet_path(@tweet.id), method: :delete,class:"menu-lists" %>
          </li>
          <% end %>
        </ul>
   </div>
   <div class="container">
      <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= render "shared/error_messages", model: f.object %>
        <%= f.text_area :text, placeholder: "コメントする", class:"comment-text" %>
         <div class="btn-border">
        <%= f.submit "送信！",class:"comment-btn" %>
        </div>
        <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
           <%= comment.text %>
        </p>
          <time datetime="<%= comment.created_at %>">
            <%= time_ago_in_words(comment.created_at) + "前"%>
          </time>
      <% end %>
    </div>
   </div>
   </div>
  
<%= render partial: "shared/footer"%>
  

app/views/tweets/update.html.erb
<%= render partial: "shared/second_header"%>

<div class="contents-destroy">
  <div class="success">
    <h4>編集が完了しました。</h4>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "shared/second_header"%>
<div class= "tweet-mypg"><i class="fas fa-baby"></i><%="#{@nickname}さんのMY PAGE"%><i class="fas fa-baby"></i></div>
 <div class="contents-row">
   <% @tweets.each do |tweet| %>
   <div class="tweet-tweet-comment">
   <div class='tweet-img-content'> 
       <%= image_tag tweet.image.variant(resize: '400x400'), class: 'tweet-image' if tweet.image.attached? %>
       <% if tweet.video.attached? %> <video src="<%= rails_blob_path(tweet.video)%>" type="video/mp4" controls class="tweet-video" ></video>
       </div>
       <% end %>
       
       <div class="more"> 
      <p><%= tweet.content %></p>
      </div>
        <ul class="more_list">
          <li>
            <i class="fa fa-comment-o"></i><%= link_to 'コメント', tweet_path(tweet.id), method: :get,class:"menu-lists" %>
          </li>
           <% if user_signed_in? && current_user.id == tweet.user_id %>
          <li>
            <i class="fa fa-edit"></i><%= link_to '編集', edit_tweet_path(tweet.id), method: :get,class:"menu-lists" %>
          </li>
          <li>
            <i class="fa fa-trash-o"></i><%= link_to '削除', tweet_path(tweet.id), data: {confirm: '本当に削除しますか？'}, method: :delete,class:"menu-lists" %>
          </li>
          <% end %>
        </ul>
   </div>
   </div>
  <% end %>
  
  <%= render partial: "shared/footer"%>
  